# base config
BASE:
  ACCELERATOR: gpu
  DEVICE:
    - 0

  DEBUG: False
  SEED_VALUE: 1234
  TASK: image_classification
# processor config
PROCESSOR:
  NAME:
  CONFIG:
# dataset config
DATAMODULE:
  NAME: cifar10
  CONFIG: default.yaml
# model config
MODEL:
  NAME: alexnet
  CONFIG: default.yaml

# train config
TRAIN:
  EPOCH: 3001
  PRETRAINED: ./logger/checkpoints/epoch=41.ckpt
  LOSS:
    TYPE: CrossEntropyLoss
  OPTIM:
    TYPE: Adan
    ARGS:
      lr: 1e-5
  METRICS:
    TYPE: Accuracy
    ARGS:
      task: multiclass
      top_k: 1
