# base config
BASE:
  ACCELERATOR: gpu
  DEVICE:
    - 0

  DEBUG: False
  SEED_VALUE: 1234
  TASK: image_classification
# processor config
PROCESSOR:
  NAME:
  CONFIG:
# dataset config
DATAMODULE:
  NAME: cifar10
  BATCH_SIZE: 32
  NUM_WORKERS: 16
  VAL_RATE: 0.2
# model config
MODEL:
  NAME: alexnet
  ARCH_CONFIG:
    dropout: 0.2
    num_classes:

# train config
TRAIN:
  EPOCH: 3001
  PRETRAINED: checkpoints/epoch=85.ckpt
  LOSS:
    TYPE: CrossEntropyLoss
  OPTIM:
    TYPE: Adan
    ARGS:
      lr: 1e-5
  METRICS:
    TYPE: Accuracy
    ARGS:
      task: multiclass
      top_k: 1
      num_classes:
