# base config
NAME: Transformer
ACCELERATOR: gpu
DEVICE:
  - 0

DEBUG: False
SEED_VALUE: 1234
TASK: text_classification
ROOT: D:\\learndeep\\src
# dataset config
DATASET:
  ORIGIN: TorchTextDataModule
  NAME: AG_NEWS
  TOKENIZER_NAME: google-bert/bert-base-uncased
  MAX_LENGTH: 512
  BATCH_SIZE: 64
  NUM_WORKERS: 4
  VAL_RATE: 0.2
# train config
TRAIN:
  BATCH_SIZE: 64 # Size of batches
  START_EPOCH: 1 # Start epoch
  END_EPOCH: 11 # End epoch
  RESUME: '' # Experiment path to be resumed training
  # PRETRAINED_VAE: ''
  PRETRAINED: '' # Pretrained model path

  OPTIM:
    TYPE: 'Adan' # Optimizer type
    LR: 4e-4 # Learning rate

EVAL:

TEST:

# model config
MODEL:
  MODEL_TYPE: Transformer
  ARCH_CONFIG:
    NUM_ENCODER_LAYERS: 5
    NUM_DECODER_LAYERS: 5
    NUM_HEADS: 8
#    DIM_FEEDFORWARD: 512
    EMBED_SIZE: 512
    DROPOUT: 0.1

    INPUT_VOCAB_SIZE:
    NUM_CLASSES:
    MAX_LENGTH:
  LOSS:
  OPTIMIZERS:

# logger config
LOGGER:
  ROOT_FOLDER: ./logger

  SAVE_CHECKPOINT_EPOCH: 1      # 保存间隔
  CHECK_VAL_EPOCH: 1
  LOG_EVERY_STEPS: 1000
  TENSORBOARD: true
  WANDB:
    OFFLINE: false
    PROJECT: null
    RESUME_ID: null

#
METRIC: