  # Runs the full optimization routine.
fit:
  # Set to an int to run seed_everything with this value before classes instantiation.Set to True to use a random seed. (type: Union[bool, int], default: True)
  seed_everything: true
  # Customize every aspect of training via flags
  trainer:
    # Supports passing different accelerator types ("cpu", "gpu", "tpu", "hpu", "mps", "auto")
    # as well as custom accelerator instances. (type: Union[str, Accelerator], default: auto, known subclasses:
    # lightning.pytorch.accelerators.CPUAccelerator,
    # lightning.pytorch.accelerators.CUDAAccelerator,
    # lightning.pytorch.accelerators.MPSAccelerator,
    # lightning.pytorch.accelerators.XLAAccelerator)
    accelerator: auto
    # Supports different training strategies with aliases as well custom strategies.
    # Default: ``"auto"``. (type: Union[str, Strategy], default: auto, known subclasses:
    # lightning.pytorch.strategies.DDPStrategy,
    # lightning.pytorch.strategies.DeepSpeedStrategy,
    # lightning.pytorch.strategies.XLAStrategy,
    # lightning.pytorch.strategies.FSDPStrategy,
    # lightning.pytorch.strategies.ModelParallelStrategy,
    # lightning.pytorch.strategies.SingleDeviceStrategy,
    # lightning.pytorch.strategies.SingleDeviceXLAStrategy)
    strategy: auto

    # The devices to use. Can be set to a positive number (int or str), a sequence of device indices
    # (list or str), the value ``-1`` to indicate all available devices should be used, or ``"auto"`` for
    # automatic selection based on the chosen accelerator. Default: ``"auto"``. (type: Union[List[int], str, int], default: auto)
    devices: auto

    # Number of GPU nodes for distributed training.
    # Default: ``1``. (type: int, default: 1)
    num_nodes: 1

    # Double precision (64, '64' or '64-true'), full precision (32, '32' or '32-true'),
    # 16bit mixed precision (16, '16', '16-mixed') or bfloat16 mixed precision ('bf16', 'bf16-mixed').
    # Can be used on CPU, GPU, TPUs, or HPUs.
    # Default: ``'32-true'``. (
    # type: Union[Literal[64, 32, 16],
    # Literal['transformer-engine', 'transformer-engine-float16', '16-true', '16-mixed', 'bf16-true', 'bf16-mixed', '32-true', '64-true'],
    # Literal['64', '32', '16', 'bf16'], null], default: null)
    precision:

    # Logger (or iterable collection of loggers) for experiment tracking. A ``True`` value uses
    # the default ``TensorBoardLogger`` if it is installed, otherwise ``CSVLogger``.
    # ``False`` will disable logging. If multiple loggers are provided, local files
    # (checkpoints, profiler traces, etc.) are saved in the ``log_dir`` of the first logger.
    # Default: ``True``. (type: Union[Logger, Iterable[Logger], bool, null], default: null, known subclasses:
    # lightning.pytorch.loggers.logger.DummyLogger,
    # lightning.pytorch.loggers.CometLogger,
    # lightning.pytorch.loggers.CSVLogger,
    # lightning.pytorch.loggers.MLFlowLogger,
    # lightning.pytorch.loggers.NeptuneLogger,
    # lightning.pytorch.loggers.TensorBoardLogger,
    # lightning.pytorch.loggers.WandbLogger)
    logger:
      - class_path: lightning.pytorch.loggers.TensorBoardLogger
        init_args:
          save_dir: .
          name: loggers
          version: null
          log_graph: false
          default_hp_metric: true
          prefix: ''
          sub_dir: null
          comment: ''
          purge_step: null
          max_queue: 10
          flush_secs: 120
          filename_suffix: ''

    # Add a callback or list of callbacks.
    # Default: ``None``. (type: Union[List[Callback], Callback, null],
    # default: null, known subclasses:
    # lightning.Callback,
    # lightning.pytorch.callbacks.BatchSizeFinder,
    # lightning.pytorch.callbacks.Checkpoint,
    # lightning.pytorch.callbacks.ModelCheckpoint,
    # lightning.pytorch.callbacks.OnExceptionCheckpoint,
    # lightning.pytorch.callbacks.DeviceStatsMonitor,
    # lightning.pytorch.callbacks.EarlyStopping,
    # lightning.pytorch.callbacks.BaseFinetuning,
    # lightning.pytorch.callbacks.BackboneFinetuning,
    # lightning.pytorch.callbacks.GradientAccumulationScheduler,
    # lightning.pytorch.callbacks.LambdaCallback,
    # lightning.pytorch.callbacks.LearningRateFinder,
    # lightning.pytorch.callbacks.LearningRateMonitor,
    # lightning.pytorch.callbacks.ModelSummary,
    # lightning.pytorch.callbacks.RichModelSummary,
    # lightning.pytorch.callbacks.BasePredictionWriter,
    # lightning.pytorch.callbacks.ProgressBar,
    # lightning.pytorch.callbacks.RichProgressBar,
    # lightning.pytorch.callbacks.TQDMProgressBar,
    # lightning.pytorch.callbacks.Timer,
    # lightning.pytorch.callbacks.ModelPruning,
    # lightning.pytorch.callbacks.SpikeDetection,
    # lightning.pytorch.callbacks.StochasticWeightAveraging,
    # lightning.pytorch.callbacks.ThroughputMonitor,
    # lightning.pytorch.cli.SaveConfigCallback)
    callbacks:
      - lightning.pytorch.callbacks.RichProgressBar
      - lightning.pytorch.callbacks.RichModelSummary
      - lightning.pytorch.callbacks.ModelCheckpoint

    # Runs n if set to ``n`` (int) else 1 if set to ``True`` batch(es)
    # of train, val and test to find any bugs (ie: a sort of unit test).
    # Default: ``False``. (type: Union[int, bool], default: False)
    fast_dev_run: false

    # Stop training once this number of epochs is reached. Disabled by default (None).
    # If both max_epochs and max_steps are not specified, defaults to ``max_epochs = 1000``.
    # To enable infinite training, set ``max_epochs = -1``. (type: Optional[int], default: null)
    max_epochs:

    # Force training for at least these many epochs. Disabled by default (None). (type: Optional[int], default: null)
    min_epochs:

    # Stop training after this number of steps. Disabled by default (-1). If ``max_steps = -1``
    # and ``max_epochs = None``, will default to ``max_epochs = 1000``. To enable infinite training, set
    # ``max_epochs`` to ``-1``. (type: int, default: -1)
    max_steps: -1

    # Force training for at least these number of steps. Disabled by default (``None``). (type: Optional[int], default: null)
    min_steps:

    # Stop training after this amount of time has passed. Disabled by default (``None``).
    # The time duration can be specified in the format DD:HH:MM:SS (days, hours, minutes seconds), as a
    # :class:`datetime.timedelta`, or a dictionary with keys that will be passed to
    # :class:`datetime.timedelta`. (type: Union[str, timedelta, Dict[str, int], null], default: null)
    max_time:

    # How much of training dataset to check (float = fraction, int = num_batches).
    # Default: ``1.0``. (type: Union[int, float, null], default: null)
    limit_train_batches:

    # How much of validation dataset to check (float = fraction, int = num_batches).
    # Default: ``1.0``. (type: Union[int, float, null], default: null)
    limit_val_batches:

    # How much of test dataset to check (float = fraction, int = num_batches).
    # Default: ``1.0``. (type: Union[int, float, null], default: null)
    limit_test_batches:

    # How much of prediction dataset to check (float = fraction, int = num_batches).
    # Default: ``1.0``. (type: Union[int, float, null], default: null)
    limit_predict_batches:

    # Overfit a fraction of training/validation data (float) or a set number of batches (int).
    # Default: ``0.0``. (type: Union[int, float], default: 0.0)
    overfit_batches: 0.0

    # How often to check the validation set. Pass a ``float`` in the range [0.0, 1.0] to check
    # after a fraction of the training epoch. Pass an ``int`` to check after a fixed number of training
    # batches. An ``int`` value can only be higher than the number of training batches when
    # ``check_val_every_n_epoch=None``, which validates after every ``N`` training batches
    # across epochs or during iteration-based training.
    # Default: ``1.0``. (type: Union[int, float, null], default: null)
    val_check_interval:

    # Perform a validation loop every after every `N` training epochs. If ``None``,
    # validation will be done solely based on the number of training batches, requiring ``val_check_interval``
    # to be an integer value.
    # Default: ``1``. (type: Optional[int], default: 1)
    check_val_every_n_epoch: 1

    # Sanity check runs n validation batches before starting the training routine.
    # Set it to `-1` to run all batches in all validation dataloaders.
    # Default: ``2``. (type: Optional[int], default: null)
    num_sanity_val_steps:

    # How often to log within steps.
    # Default: ``50``. (type: Optional[int], default: null)
    log_every_n_steps:

    # If ``True``, enable checkpointing.
    # It will configure a default ModelCheckpoint callback if there is no user-defined ModelCheckpoint in
    # :paramref:`~lightning.pytorch.trainer.trainer.Trainer.callbacks`.
    # Default: ``True``. (type: Optional[bool], default: null)
    enable_checkpointing: True

    # Whether to enable to progress bar by default.
    # Default: ``True``. (type: Optional[bool], default: null)
    enable_progress_bar: True

    # Whether to enable model summarization by default.
    # Default: ``True``. (type: Optional[bool], default: null)
    enable_model_summary: True

    # Accumulates gradients over k batches before stepping the optimizer.
    # Default: 1. (type: int, default: 1)
    accumulate_grad_batches: 1

    # The value at which to clip gradients. Passing ``gradient_clip_val=None`` disables
    # gradient clipping. If using Automatic Mixed Precision (AMP), the gradients will be unscaled before.
    # Default: ``None``. (type: Union[int, float, null], default: null)
    gradient_clip_val:

    # The gradient clipping algorithm to use. Pass ``gradient_clip_algorithm="value"``
    # to clip by value, and ``gradient_clip_algorithm="norm"`` to clip by norm. By default it will
    # be set to ``"norm"``. (type: Optional[str], default: null)
    gradient_clip_algorithm:

    # If ``True``, sets whether PyTorch operations must use deterministic algorithms.
    # Set to ``"warn"`` to use deterministic algorithms whenever possible, throwing warnings on operations
    # that don't support deterministic mode. If not set, defaults to ``False``. Default: ``None``. (type: Union[bool, Literal['warn'], null], default: null)
    deterministic:

    # The value (``True`` or ``False``) to set ``torch.backends.cudnn.benchmark`` to.
    # The value for ``torch.backends.cudnn.benchmark`` set in the current session will be used
    # (``False`` if not manually set). If :paramref:`~lightning.pytorch.trainer.trainer.Trainer.deterministic`
    # is set to ``True``, this will default to ``False``. Override to manually set a different value.
    # Default: ``None``. (type: Optional[bool], default: null)
    benchmark:

    # Whether to use :func:`torch.inference_mode` or :func:`torch.no_grad` during
    # evaluation (``validate``/``test``/``predict``). (type: bool, default: True)
    inference_mode: true

    # Whether to wrap the DataLoader's sampler with
    # :class:`torch.utils.data.DistributedSampler`. If not specified this is toggled automatically for
    # strategies that require it. By default, it will add ``shuffle=True`` for the train sampler and
    # ``shuffle=False`` for validation/test/predict samplers. If you want to disable this logic, you can pass
    # ``False`` and add your own distributed sampler in the dataloader hooks. If ``True`` and a distributed
    # sampler was already added, Lightning will not replace the existing one. For iterable-style datasets,
    # we don't do this automatically. (type: bool, default: True)
    use_distributed_sampler: true

    # To profile individual steps during training and assist in identifying bottlenecks.
    # Default: ``None``. (type: Union[Profiler, str, null], default: null, known subclasses:
    # lightning.pytorch.profilers.AdvancedProfiler,
    # lightning.pytorch.profilers.PassThroughProfiler,
    # lightning.pytorch.profilers.PyTorchProfiler,
    # lightning.pytorch.profilers.SimpleProfiler,
    # lightning.pytorch.profilers.XLAProfiler)
    profiler:

    # Enable anomaly detection for the autograd engine.
    # Default: ``False``. (type: bool, default: False)
    detect_anomaly: false

    # Whether to run in "barebones mode", where all features that may impact raw speed are
    # disabled. This is meant for analyzing the Trainer overhead and is discouraged during regular training
    # runs. The following features are deactivated:
    # :paramref:`~lightning.pytorch.trainer.trainer.Trainer.enable_checkpointing`,
    # :paramref:`~lightning.pytorch.trainer.trainer.Trainer.logger`,
    # :paramref:`~lightning.pytorch.trainer.trainer.Trainer.enable_progress_bar`,
    # :paramref:`~lightning.pytorch.trainer.trainer.Trainer.log_every_n_steps`,
    # :paramref:`~lightning.pytorch.trainer.trainer.Trainer.enable_model_summary`,
    # :paramref:`~lightning.pytorch.trainer.trainer.Trainer.num_sanity_val_steps`,
    # :paramref:`~lightning.pytorch.trainer.trainer.Trainer.fast_dev_run`,
    # :paramref:`~lightning.pytorch.trainer.trainer.Trainer.detect_anomaly`,
    # :paramref:`~lightning.pytorch.trainer.trainer.Trainer.profiler`,
    # :meth:`~lightning.pytorch.core.LightningModule.log`,
    # :meth:`~lightning.pytorch.core.LightningModule.log_dict`. (type: bool, default: False)
    barebones: false

    # Plugins allow modification of core behavior like ddp and amp, and enable custom lightning plugins.
    # Default: ``None``.
    # (type: Union[Precision, ClusterEnvironment, CheckpointIO, LayerSync, List[Union[Precision, ClusterEnvironment, CheckpointIO, LayerSync]], null], default:null, known subclasses:
    # lightning.pytorch.plugins.Precision,
    # lightning.pytorch.plugins.MixedPrecision,
    # lightning.pytorch.plugins.BitsandbytesPrecision,
    # lightning.pytorch.plugins.DeepSpeedPrecision,
    # lightning.pytorch.plugins.DoublePrecision,
    # lightning.pytorch.plugins.FSDPPrecision,
    # lightning.pytorch.plugins.HalfPrecision,
    # lightning.pytorch.plugins.TransformerEnginePrecision,
    # lightning.pytorch.plugins.XLAPrecision,
    # lightning.fabric.plugins.environments.KubeflowEnvironment,
    # lightning.fabric.plugins.environments.LightningEnvironment,
    # lightning.fabric.plugins.environments.LSFEnvironment,
    # lightning.fabric.plugins.environments.MPIEnvironment,
    # lightning.fabric.plugins.environments.SLURMEnvironment,
    # lightning.fabric.plugins.environments.TorchElasticEnvironment,
    # lightning.fabric.plugins.environments.XLAEnvironment,
    # lightning.fabric.plugins.TorchCheckpointIO,
    # lightning.fabric.plugins.XLACheckpointIO,
    # lightning.pytorch.plugins.AsyncCheckpointIO,
    # lightning.pytorch.plugins.TorchSyncBatchNorm)
    plugins:

    # Synchronize batch norm layers between process groups/whole world.
    # Default: ``False``. (type: bool, default: False)
    sync_batchnorm: false

    # Set to a positive integer to reload dataloaders every n epochs.
    # Default: ``0``. (type: int, default: 0)
    reload_dataloaders_every_n_epochs: 0

    # Default path for logs and weights when no logger/ckpt_callback passed.
    # Default: ``os.getcwd()``.
    # Can be remote file paths such as `s3://mybucket/path` or 'hdfs://path/' (type: Union[str, Path, null], default: null)
    default_root_dir:

  # One or more arguments specifying "class_path" and "init_args" for any subclass of LightningModule. (type: Optional[LightningModule], default: null, known subclasses: lightning.LightningModule)
  model:
    class_path: models.alexnet_module.AlexNetModule
    init_args:
      num_classes: 10

  # One or more arguments specifying "class_path" and "init_args" for any subclass of LightningDataModule. (type: Optional[LightningDataModule], default: null, known subclasses: lightning.LightningDataModule)
  data:
    class_path: datamodules.TorchVisionDataModule
    init_args:
      name: MNIST
      val_rate: 0.2
      batch_size: 32
      num_workers: 16

  # One or more arguments specifying "class_path" and "init_args" for any subclass of Optimizer.
  # (type: Optional[Optimizer], default: null, known subclasses:
  # torch.optim.Optimizer,
  # torch.optim.Adadelta,
  # torch.optim.Adagrad,
  # torch.optim.Adam,
  # torch.optim.AdamW,
  # torch.optim.Adamax,
  # torch.optim.ASGD,
  # torch.optim.NAdam,
  # torch.optim.RAdam,
  # torch.optim.RMSprop,
  # torch.optim.Rprop,
  # torch.optim.SGD,
  # torch.optim.SparseAdam,
  # torch.optim.LBFGS)
  optimizer:
    class_path: Adam

  # One or more arguments specifying "class_path" and "init_args" for any subclass of {LRScheduler,ReduceLROnPlateau}.
  # (type: Union[LRScheduler, ReduceLROnPlateau, null], default: null, known subclasses:
  # torch.optim.lr_scheduler.LRScheduler,
  # torch.optim.lr_scheduler.LambdaLR,
  # torch.optim.lr_scheduler.MultiplicativeLR,
  # torch.optim.lr_scheduler.StepLR,
  # torch.optim.lr_scheduler.MultiStepLR,
  # torch.optim.lr_scheduler.ConstantLR,
  # torch.optim.lr_scheduler.LinearLR,
  # torch.optim.lr_scheduler.ExponentialLR,
  # torch.optim.lr_scheduler.SequentialLR,
  # torch.optim.lr_scheduler.PolynomialLR,
  # torch.optim.lr_scheduler.CosineAnnealingLR,
  # torch.optim.lr_scheduler.ChainedScheduler,
  # torch.optim.lr_scheduler.CyclicLR,
  # torch.optim.lr_scheduler.CosineAnnealingWarmRestarts,
  # torch.optim.lr_scheduler.OneCycleLR,
  # torch.optim.swa_utils.SWALR,
  # lightning.pytorch.cli.ReduceLROnPlateau)
  lr_scheduler:

  # Path/URL of the checkpoint from which training is resumed. Could also be one of two special
  # keywords ``"last"`` and ``"hpc"``. If there is no checkpoint file at the path, an exception is raised. (type: Union[str, Path, null], default: null)
  ckpt_path: