MODEL:
  MODEL_TYPE: AlexNet
  NUM_CLASSES:
  ARCH_CONFIG:
    DROPOUT: 0.2
  LOSS:
    TYPE: CrossEntropyLoss
  OPTIM:
    TYPE: Adan # Optimizer type
    ARGS:
      LR: 4e-4 # Learning rate
  METRIC:
    TYPE: Accuracy
    ARGS:
      TASK: multiclass
      TOP_K: 1
