# lightning.pytorch==2.3.3
seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  logger:
    - class_path: lightning.pytorch.loggers.TensorBoardLogger
      init_args:
        save_dir: .
        name: logger
        version: null
        log_graph: false
        default_hp_metric: true
        prefix: ''
        sub_dir: null
        comment: ''
        purge_step: null
        max_queue: 10
        flush_secs: 120
        filename_suffix: ''
  callbacks:
    - utils.callbacks.RichProgressBar1
    - class_path: lightning.pytorch.callbacks.RichModelSummary
      init_args:
        max_depth: 1
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: null
        filename: null
        monitor: val_loss
        verbose: false
        save_last: null
        save_top_k: 5
        save_weights_only: false
        mode: min
        auto_insert_metric_name: true
        every_n_train_steps: null
        train_time_interval: null
        every_n_epochs: null
        save_on_train_epoch_end: null
        enable_version_counter: true
  fast_dev_run: false
  max_epochs: null
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: true
  enable_progress_bar: true
  enable_model_summary: true
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
  class_path: modules.swintransformer_module.SwinTransformerModule
  init_args:
    model:
      class_path: torchvision.models.SwinTransformer
      init_kwargs:
        patch_size: [4, 4]
        embed_dim: 96
        depths: [2, 2, 6, 2]
        num_heads: [3, 6, 12, 24]
        window_size: [7, 7]
        mlp_ratio: 4.0
        dropout: 0.0
        attention_dropout: 0.0
        stochastic_depth_prob: 0.1
        num_classes: &num_classes 2
    loss:
      class_path: torch.nn.CrossEntropyLoss
    metrics:
      class_path: torchmetrics.Accuracy
      init_args:
        task: multiclass
        num_classes: *num_classes
data:
  class_path: datamodules.CarvanaDataModule
  init_args:
    kwargs:
      dir_img: data/carvana/train
      dir_mask: data/carvana/train_masks
      img_scale: 1
      batch_size: 4
      num_workers: 1
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 1e-5
    betas:
      - 0.9
      - 0.999
    eps: 1.0e-08
    weight_decay: 0
    amsgrad: false
    foreach: null
    maximize: false
    capturable: false
    differentiable: false
    fused: null
lr_scheduler: null
ckpt_path: null
