# lightning.pytorch==2.3.3
seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger:
  - class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: .
      name: logger
      version: version_7
      log_graph: false
      default_hp_metric: true
      prefix: ''
      sub_dir: null
      comment: ''
      purge_step: null
      max_queue: 10
      flush_secs: 120
      filename_suffix: ''
  callbacks:
  - class_path: lightning.pytorch.callbacks.RichProgressBar
    init_args:
      refresh_rate: 1
      leave: false
      theme:
        description: green_yellow
        progress_bar: green1
        progress_bar_finished: green1
        progress_bar_pulse: #6206E0
        batch_progress: green_yellow
        time: green_yellow
        processing_speed: grey82
        metrics: grey82
        metrics_text_delimiter: "\n"
        metrics_format: .3f
      console_kwargs: null
  - class_path: lightning.pytorch.callbacks.RichModelSummary
    init_args:
      max_depth: 1
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      dirpath: null
      filename: null
      monitor: val_loss
      verbose: false
      save_last: null
      save_top_k: 5
      save_weights_only: false
      mode: min
      auto_insert_metric_name: true
      every_n_train_steps: null
      train_time_interval: null
      every_n_epochs: null
      save_on_train_epoch_end: null
      enable_version_counter: true
  fast_dev_run: false
  max_epochs: null
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: true
  enable_progress_bar: true
  enable_model_summary: true
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
  class_path: models.TransformerModule
  init_args:
    input_vocab_size: 32000
    embed_size: 512
data:
  class_path: datamodules.HuggingfaceTranslateDataModule
  init_args:
#    kwargs: { 'path': 'data/wmt14', 'name': 'fr-en', 'split': null, 'cache_dir': '..', 'batch_size':32, 'num_workers': 16 }
    kwargs:
      path: data/wmt14
      name: fr-en
      split: null
      cache_dir: .
      batch_size: 8
      num_workers: 2
      processor_src:
        class_path: processors.WMT14Processor
        init_args:
          file_name: ./processors/cache/wmt14_en.json
      processor_tgt:
        class_path: processors.WMT14Processor
        init_args:
          file_name: ./processors/cache/wmt14_fr.json
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 1e-5
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    weight_decay: 0
    amsgrad: false
    foreach: null
    maximize: false
    capturable: false
    differentiable: false
    fused: null
lr_scheduler: null
ckpt_path: null
